language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6

services:
  - docker
  - redis

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker-compose build
  - docker-compose up

script:
  - docker-compose run --service-ports cache_engine bash
  - phpunit